/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zzx.application;

import org.junit.Test;
import zzx.library.Library;

import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Library classUnderTest = new Library();
        assertNotNull("app should have a greeting", classUnderTest.getGreetings());
    }
}
