/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zzx.application;

import zzx.library.Library;

public class App {
    public static void main(String[] args) {
        System.out.println(new Library().getGreetings());
    }
}
